== Getting Started

There are a few ways to initialize Sqlg. The easiest is to include one of the provided connection pools and choose a supported database.

e.g.

[subs="specialchars, attributes"]
.C3P0
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-c3p0</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

[subs="specialchars, attributes"]
.Postgresql
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-postgres</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

You can also provide your own custom datasource by implementing `org.umlg.sqlg.structure.SqlgDataSource`. To let `Sqlg` know about your custom datasource you need to specify the fully qualified class name in `sqlg.properties`

```
sqlg.dataSource=your.custom.SqlgDataSource
```

Sqlg can also do a `JNDI` lookup to find the datasource. For this to work the `jdbc.url` property must begin with `jndi:`

=== Maven coordinates

Sqlg has support for https://www.mchange.com/projects/c3p0/[c3p0] and https://github.com/brettwooldridge/HikariCP[hikari] connection pools.

.C3P0
[subs="specialchars, attributes"]
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-c3p0</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

.Hikari
[subs="specialchars, attributes"]
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-hikari</artifactId>
     <version>{version}</version>
 </dependency>

The various `Sqlg` supported databases.

[subs="specialchars, attributes"]
.Postgresql
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-postgres</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

[subs="specialchars, attributes"]
.HSQLDB
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-hsqldb</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

[subs="specialchars, attributes"]
.H2
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-h2</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

The above mentioned maven coordinates will include `gremlin-groovy`. To exclude `gremlin-groovy` only include the dialect.

[subs="specialchars, attributes"]
.Postgresql
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-postgres-dialect</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

[subs="specialchars, attributes"]
.HSQLDB
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-hsqldb-dialect</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

[subs="specialchars, attributes"]
.H2
 <dependency>
     <groupId>org.umlg</groupId>
     <artifactId>sqlg-h2-dialect</artifactId>
     <version>{sqlg-version}</version>
 </dependency>

=== Start

`SqlgGraph` is a singleton that can be shared among multiple threads. You instantiate `SqlgGraph` using the standard
TinkerPop static constructors.

* `Graph g = SqlgGraph.open(final Configuration configuration)`
* `Graph g = SqlgGraph.open(final String pathToSqlgProperties)`

The configuration object requires the following properties.

.Postgresql
 jdbc.url=jdbc:postgresql://localhost:5432/yourdb
 jdbc.username=postgres
 jdbc.password=******

.HSQLDB
 jdbc.url=jdbc:hsqldb:file:/tmp/yourdb
 jdbc.username=SA
 jdbc.password=

.H2
 jdbc.url=jdbc:h2:file:target/tmp/yourdb
 jdbc.username=SA
 jdbc.password=

In the case of `Postgresql` the database must already exist.

Once you have access to the graph you can use it as per normal.
[source,java,options="nowrap"]
----
@Test
public void useAsPerNormal() {
    Vertex person = this.sqlgGraph.addVertex(T.label, "Person", "name", "John");
    Vertex address = this.sqlgGraph.addVertex(T.label, "Address", "street", "13th");
    person.addEdge("livesAt", address, "since", LocalDate.of(2010, 1, 21));
    this.sqlgGraph.tx().commit(); # <1>
    List<Vertex> addresses = this.sqlgGraph.traversal().V().hasLabel("Person").out("livesAt").toList();
    assertEquals(1, addresses.size());
}
----
<1> It is very important to always commit or rollback the transaction.
If you do not, connections to the database will remain open and eventually
the connection pool will run out of connections.