package org.umlg.sqlg;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.umlg.sqlg.test.schema.TestMultiThread;

/**
 * Date: 2014/07/16
 * Time: 12:08 PM
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
//        TestAddVertexViaMap.class,
//        TestAllEdges.class,
//        TestAllVertices.class,
//        TestArrayProperties.class,
//        TestCountVerticesAndEdges.class,
//        TestDeletedVertex.class,
//        TestEdgeCreation.class,
//        TestEdgeToDifferentLabeledVertexes.class,
//        TestGetById.class,
//        TestHas.class,
//        TestHasLabel.class,
//        TestLoadArrayProperties.class,
//        TestLoadElementProperties.class,
//        TestLoadSchema.class,
//        TestPool.class,
//        TestRemoveElement.class,
//        TestSetProperty.class,
//        TestVertexCreation.class,
//        TestVertexEdgeSameName.class,
//        TestVertexNavToEdges.class,
//        // are these tests gone?
//        //TestByteArray.class,
//        //TestQuery.class,
//        TestSchema.class,
//        TestIndex.class,
//        TestVertexOutWithHas.class,
//        TestEdgeHas.class,
//        TestBatch.class,
//        TestBatchNormalUpdate.class,
//        TestMultiThreadedBatch.class,
        TestMultiThread.class,
//        TestMultipleThreadMultipleJvm.class,
//
//        TestRemoveEdge.class,
//        TestEdgeSchemaCreation.class,
//        TestRollback.class,
//
//        TestNewVertex.class,
//        TestEdgeCache.class,
//        TestVertexCache.class,
//        TestTinkerpopBug.class,
//        TestLoadSchemaViaNotify.class,
//        TestCreateEdgeBetweenVertices.class,
//        TestRemovedVertex.class,
//        TestCaptureSchemaTableEdges.class,
//        TestGremlinCompileWithHas.class,
//        TestGremlinCompileE.class,
//        TestEmptyGraph.class,
//        TestOutE.class,
//        TestForeignKeysAreOptional.class,
//        TestGremlinCompileWithAs.class,
//        TestGremlinCompileWithInOutV.class,
//        TestGremlinCompileV.class,
//        TestGremlinCompileGraphStep.class,
//        TestGremlinCompileWhere.class,
//        TestGremlinCompileTextPredicate.class,
//        TestGremlinCompileChoose.class,
//        TestColumnNameTranslation.class,
//        TestGraphStepOrderBy.class,
//        TestVertexStepOrderBy.class,
//        TestPathStep.class,
//        LocalDateTest.class,
//        TestBatchStreamVertex.class,
//        TestBatchStreamEdge.class,
//        JsonTest.class,
//        TestSchemaManagerGetTablesFor.class,
//        TestBatchServerSideEdgeCreation.class,
//        TestBatchedStreaming.class,
//        TestBulkWithin.class,
//        TestBulkWithout.class,
//        TestRemoveProperty.class,
//        TestSchemaManagerGetTablesFor.class,
//        TestAggregate.class,
//        TestTreeStep.class,
//        TestRepeatStepGraphOut.class,
//        TestRepeatStepGraphIn.class,
//        TestRepeatStepVertexOut.class,
//        TestRepeatStepGraphBoth.class,
//        TestRepeatStepWithLabels.class,
//        TestGraphStepWithIds.class,
//        TestOtherVertex.class,
//        TestGremlinMod.class,
//        TestTopologyUpgrade.class,
//        TestTopologyMultipleGraphs.class,
//        TestTraversals.class,
//        TestGremlinOptional.class,
//        TestAlias.class,
//        TestGithub.class,
//        TestLocalVertexStepOptional.class,
//        TestLocalVertexStepRepeatStep.class,
//        TestLocalEdgeVertexStep.class,
//        TestLocalEdgeOtherVertexStep.class,
//        TestBatchNormalDateTime.class,
//        TestBatchEdgeDateTime.class,
//        TestBatchJson.class,
//        TestMemoryUsage.class,
//        TestBatchTemporaryVertex.class,
//        TestBatchNormalPrimitiveArrays.class,
//        TestBatchNormalPrimitive.class,
//        TestBatchNormalUpdatePrimitiveArrays.class,
//        TestJsonUpdate.class,
//        TestBatchNormalUpdateDateTime.class,
//        TestOptionalWithOrder.class,
//        TestMultipleLabels.class,
//        TestColumnNamePropertyNameMapScope.class,
//        TestJNDIInitialization.class,
//        TestSchemaTableTreeAndHasContainer.class,
//        TestEscapedValues.class,
//        TestRepeatStepOnEdges.class,
//        TestLoadingAdjacent.class,
//        TestLabelsSchema.class,
//        MidTraversalGraphTest.class,
//        //TODO fails, issue #65
////        TestEdgeFromDifferentSchema.class
//        TestBatchModeMultipleGraphs.class,
//        TestDetachedEdge.class,
//        TestSchemaEagerCreation.class,
//        TestIndexTopologyTraversal.class,
//        TestNotifyJson.class,
//        TestGlobalUniqueIndex.class,
//        TestBatchGlobalUniqueIndexes.class,
//        TestVertexEdges.class,
//        TestSqlgSchema.class,
//        TestValidateTopology.class,
//        TestBatchNormalUpdateDateTimeArrays.class,
//        TestTopologyChangeListener.class
})
public class AllTest {
}
